HOSTS:
  ubuntu-14-04-master:
    roles:
      - master
      - database
      - dashboard
    platform: ubuntu-14.04-amd64
    #image: ubuntu:14.04
    image: electrical/ubuntu:14.04
    hypervisor: docker
  ubuntu-14-04-agent:
    roles:
      - agent
    platform: ubuntu-14.04-amd64
    #image: ubuntu:14.04
    image: electrical/ubuntu:14.04
    hypervisor: docker

CONFIG:
  type: pe
  pe_ver: 2016.1.2
  pe_dir: https://s3.amazonaws.com/pe-builds/released/2016.1.2
  log_level: verbose
  trace_limit: 100
