HOSTS:
  ubuntu-14-04-master:
    roles:
      - master
      - database
      - dashboard
    platform: ubuntu-14.04-amd64
    vmname: ubuntu-14.04-west
    hypervisor: ec2
    amisize: m3.medium
    snapshot: pe
    ssh:
      user: ubuntu

  ubuntu-14-04-agent:
    roles:
      - agent
    platform: ubuntu-14.04-amd64
    snapshot: pe
    vmname: ubuntu-14.04-west
    hypervisor: ec2
    amisize: m3.medium
    ssh:
      user: ubuntu

CONFIG:
  type: pe
  pe_ver: 2016.1.2
  pe_dir: https://s3.amazonaws.com/pe-builds/released/2016.1.2
  log_level: verbose
  trace_limit: 100
